<a href="https://colab.research.google.com/github/2303a51063/python_datascience/blob/main/2303a51063_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np
 A = np.random.randint(1, 10, (3, 3))
 B = np.random.randint(1, 10, (3, 3))
 print("Matrix A:\n", A)
 print("\nMatrix B:\n", B)

Matrix A:
 [[8 7 8]
 [4 2 9]
 [9 3 1]]

Matrix B:
 [[4 8 6]
 [9 5 7]
 [6 7 2]]


In [ ]:
 add_result = np.add(A, B)
 sub_result = np.subtract(A, B)
 print("Matrix A:\n", A)

Matrix A:
 [[8 7 8]
 [4 2 9]
 [9 3 1]]


In [ ]:
 print("Matrix B:\n", B)

Matrix B:
 [[4 8 6]
 [9 5 7]
 [6 7 2]]


In [ ]:
 print("\nAddition Result:\n", add_result)


Addition Result:
 [[12 15 14]
 [13  7 16]
 [15 10  3]]


In [ ]:
 print("\nSubtraction Result:\n", sub_result)


Subtraction Result:
 [[ 4 -1  2]
 [-5 -3  2]
 [ 3 -4 -1]]


In [ ]:
print(f"A[0][0] + B[0][0] = {A[0][0]} + {B[0][0]} = {add_result[0][0]}")
print(f"A[0][0] - B[0][0] = {A[0][0]} - {B[0][0]} = {sub_result[0][0]}")

A[0][0] + B[0][0] = 8 + 4 = 12
A[0][0] - B[0][0] = 8 - 4 = 4


In [ ]:
# 2)2D Matrix Multiplication
import numpy as np
image = np.array([
    [[123, 50, 200],
     [34, 210, 89],
     [255, 180, 75]],
    [[45, 60, 90],
     [220, 130, 40],
     [10, 240, 180]],
    [[100, 200, 150],
     [60, 90, 120],
     [80, 160, 220]]
], dtype=np.uint8)
print("Original Image (3x3x3):\n", image)

Original Image (3x3x3):
 [[[123  50 200]
  [ 34 210  89]
  [255 180  75]]

 [[ 45  60  90]
  [220 130  40]
  [ 10 240 180]]

 [[100 200 150]
  [ 60  90 120]
  [ 80 160 220]]]


In [ ]:
 red_layer = image[:, :, 0]
 green_layer = image[:, :, 1]
 blue_layer = image[:, :, 2]
 print("\nRed Channel:\n", red_layer)
 print("\nGreen Channel:\n", green_layer)
 print("\nBlue Channel:\n", blue_layer)


Red Channel:
 [[123  34 255]
 [ 45 220  10]
 [100  60  80]]

Green Channel:
 [[ 50 210 180]
 [ 60 130 240]
 [200  90 160]]

Blue Channel:
 [[200  89  75]
 [ 90  40 180]
 [150 120 220]]


In [ ]:
 avg_red = np.mean(red_layer)
 avg_green = np.mean(green_layer)
 avg_blue = np.mean(blue_layer)
 print("\nAverage Intensities:")
 print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")


Average Intensities:
Red: 103.00, Green: 146.67, Blue: 129.33


In [ ]:
 brightened = np.clip(image + 50, 0, 255)
 print("\nBrightened Image:\n", brightened)


Brightened Image:
 [[[173 100 250]
  [ 84   4 139]
  [ 49 230 125]]

 [[ 95 110 140]
  [ 14 180  90]
  [ 60  34 230]]

 [[150 250 200]
  [110 140 170]
  [130 210  14]]]


In [ ]:
 A = np.array([[1, 2, 3],
 [4, 5, 6]])
 # 1D Array
 b = np.array([10, 20, 30])
 # Broadcasting (2D + 1D)
 C = A + b
 print("2D + 1D Broadcasting:\n", C)

2D + 1D Broadcasting:
 [[11 22 33]
 [14 25 36]]


In [ ]:
D = np.ones((2,3,4)) * 5
scalar = 10
E = D + scalar
print("\n3D + scalar Broadcasting:\n", E)


3D + scalar Broadcasting:
 [[[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]

 [[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]]


In [ ]:
 b2 = np.array([1,2,3])
 expanded = b2[:, np.newaxis]
 print("\nShape Transformation Example:")
 print("Original b2.shape:", b2.shape)
 print("Expanded b2.shape:", expanded.shape)


Shape Transformation Example:
Original b2.shape: (3,)
Expanded b2.shape: (3, 1)


In [ ]:
X = np.ones((2,3))
Y = np.ones((3,))
Z = X + Y
print("\n2D + 1D Broadcasting (Fixed Example):")
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Result Z:\n", Z)


2D + 1D Broadcasting (Fixed Example):
X shape: (2, 3)
Y shape: (3,)
Result Z:
 [[2. 2. 2.]
 [2. 2. 2.]]
